accounts/urls.py
from django.urls import path

from . import views

app_name='account'
urlpatterns = [
    path('signup/', views.Signup.as_view(), name='signup'),
    path('user/', views.UserView.as_view(), name='account'),
    path('category/', views.CategoryListView.as_view(), name='category')
]

intekimdb/urls.py
from django.urls import path

from . import views


app_name='intekimdb'
urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('actors/', views.ActorListView.as_view(), name='actor_list'),
    path('actors/create/', views.ActorCreate.as_view(), name='actor_create'),
    path('actors/<int:pk>/', views.ActorDetailView.as_view(), name='actor_detail'),
    path('actors/<int:pk>/update/', views.ActorUpdate.as_view(), name='actor_update'),
    path('actors/<int:pk>/delete/', views.ActorDelete.as_view(), name='actor_delete'),
    path('movies/', views.MovieListView.as_view(), name='movie_list'),
    path('movies/create/', views.MovieCreate.as_view(), name='movie_create'),
    path('movies/<int:pk>/', views.MovieDetailView.as_view(), name='movie_detail'),
    path('movies/<int:pk>/update/', views.MovieUpdate.as_view(), name='movie_update'),
    path('movies/<int:pk>/delete/', views.MovieDelete.as_view(), name='movie_delete'),
    path('awards/', views.AwardListView.as_view(), name='award_list'),
    path('awards/create/', views.AwardCreate.as_view(), name='award_create'),
    path('awards/<int:pk>/', views.AwardDetailView.as_view(), name='award_detail'),
    path('awards/<int:pk>/update/', views.AwardUpdate.as_view(), name='award_update'),
    path('awards/<int:pk>/delete/', views.AwardDelete.as_view(), name='award_delete'),
    path('comment/<int:pk>/<int:id>/delete/', views.CommentDelete.as_view(), name='comment_delete'),
    path('comment/<int:pk>/<int:id>/update/', views.CommentUpdate.as_view(), name='comment_update'),

]


test_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView, RedirectView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/accounts/login/')),
    path('home/', TemplateView.as_view(template_name='home.html'), name='home'),
    path('home/', include('intekimdb.urls'), name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/add_category.html
{% extends 'home.html' %}
{% load add_attr %}

{% load static %}


{% block content %}
    <div class="row d-flex justify-content-center mt-5">
        <div class="col-6">
            <div class="card border-info">
                <div class="card-header">
                    <h2 class="mb-0">Add new category</h2>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username" class="col-lg-10 col-form-label">Category name</label>
                            <div class="col-lg-10">
                                {{ form.name|add_attr:"class:form-control"}}
                            </div>
                        </div>
                        <p class="text-danger col-lg-10">
                            {{ form.name.errors.as_text }}
                        </p>
                        <div class="col-sm-4 mt-3 ml-auto">
                            <button type="submit" class="btn btn-primary col-12">ADD</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title%}Django Authentication{% endblock %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">

    <!-- js -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    {% block head %}{% endblock %}
</head>
<body class="bg-light">

    {% block nav %}
    {% endblock %}

    <div style="height: 150px"></div>
    <main class="container flex-wrap">
        {% block content %}
            
        {% endblock %}
    </main>

    <footer class="container">
        <p class="text-muted text-center mt-5" style="font-size: 13px">C 2019 INTEKER</p>
    </footer>
    {% block js %}
    {% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title%}Home{% endblock %}

{% block nav %}
{% if user.is_authenticated %}
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-secondary mb-4 pl-5 pr-5">
    <div class="container col-9">
    <a href="{% url 'home' %}" class="nav-link">
        <img src="https://cdn.itviec.com/employers/intek-institute-of-applied-technology/logo/w170/ww5hEKU4Gqg385c6WkpmsdiN/intek-institute-of-applied-technology-logo.png" alt="logo" class="navbar-brand" width="60px">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="col-6 category" id="nav-list">
            <ul class="navbar-nav d-flex">
                <li class="nav-item">
                    <a href="{% url 'intekimdb:movie_list' %}" class="nav-link text-white">Movies</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'intekimdb:actor_list' %}" class="nav-link text-white">Actors</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'intekimdb:award_list' %}" class="nav-link text-white">Awards</a>
                </li>
            </ul>
        </div>
        <div class="col-4 ml-auto logout">
            <ul class="navbar-nav d-flex justify-content-end">
                <li class="nav-item">
                    <a href="{% url 'account:account' %}" class="nav-link text-light">{{ user.username }}</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'logout' %}" class="nav-link text-light">Logout</a>
                </li>
            </ul>
        </div>
    </div>
    
    <script>
        $(function() {
            if ($(window).width() < 992) {
                $('#nav-list').addClass('justify-content-end');
                $("#nav-list").addClass('ml-auto');
                $("#nav-list").addClass('col-4');
                $("#nav-list").removeClass('col-6');
                $(".nav-link").addClass('text-right');
            } else if ($(window).width() >= 992) {
                $('.nav-link').removeClass('text-right');
                $('#nav-list').addClass('col-6');
                $('#nav-list').removeClass('col-4');

            }
        });
    </script>
    </div>
</nav>
{% else %}
<nav  class="navbar fixed-top navbar-expand-lg navbar-light bg-secondary mb-4 pl-5 pr-5">
    <div class="container col-9">
    <a href="{% url 'base' %}" class="nav-link">
        <img src="https://cdn.itviec.com/employers/intek-institute-of-applied-technology/logo/w170/ww5hEKU4Gqg385c6WkpmsdiN/intek-institute-of-applied-technology-logo.png" alt="logo" class="navbar-brand" width="60px">
    </a>

</div>
</nav>
{% endif %}
{% endblock %}


{% block content %}
{% if user.is_authenticated %}
    <div class="container m-auto d-flex justify-content-center align-self-center">
        <a href="{% url 'intekimdb:movie_list' %}" class="btn btn-info">
            <h2 class="mt-2 mb-2">START EXPLORE THE SITE</h2>
        </a>
    </div>
{% endif %}
{% endblock %}

{% block js %}
{% endblock %}

templates/signup.html
{% extends 'home.html' %}

{% load add_attr %}
{% load add_attr_str %}

{% block title %}Signup{% endblock %}

{% block content %}
<div class="row justify-content-center mt-5">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <h2>Sign up</h2>
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_username" class="col-lg-10 col-form-label">Username</label>
                        <div class="col-lg-10">
                            {{ form.username|add_attr:"class:form-control"}}
                        </div>
                        <p class="form-label col-lg-10 mt-2" style="font-size:13px"><i class="text-danger">
                            {{ form.username.errors.as_text}}
                        </i></p>
                    </div>
                    <div class="form-group">
                        <label for="id_password1" class="col-lg-10 col-form-label">Password</label>
                        <div class="col-lg-10">
                            {{ form.password1|add_attr:"class:form-control"}}
                        </div>
                        <p class="form-label col-lg-10 mt-2" style="font-size:13px"><i class="text-danger">
                                {{ form.password1.errors.as_ul }}
                            </i></p>
                    </div>
                    <div class="forms-group">
                        <label for="id_password2" class="col-lg-10 col-form-label">Comfirm password</label>
                        <div class="col-lg-10">
                            {{ form.password2|add_attr:"class:form-control"}}
                        </div>
                        <ul class="list-group col-lg-10 col-form-label">
                            {% for error in form.password2.errors %}
                            <li class="list-group-item text-danger font-italic border-0 pt-0" style="font-size:13px">
                                * {{ error }}
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="col-sm-2 mt-3">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/user.html
{% extends 'home.html' %}
{% load add_attr %}

{% load static %}

'''
this will views out user info, include:
    - User name
    - Email (maybe)
    - posted movie
    - posted actors
    - comments
    - change password link
    - change info link
    
'''

{% block title %}Account {{ user.username }}{% endblock %}

{% block content %}
    {% if user.is_superuser %}
        <div class="col-8 mx-auto mb-5">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-text">
                        Hi {{ user.username }}
                    </h5>
                </div>
                <div class="card-body">
                    <h4 class="card-text text-center">
                        You are loged in as {{ user.username }}.
                    </h4>
                </div>
                <div class="card-footer d-flex flex-row justify-content-center align-items-center">
                    <a href="{% url 'home' %}" class="col-sm-4">
                        <p class="card-link text-muted mb-0">
                            Explore this site
                        </p>
                    </a>
                    <a href="/admin/" class="btn btn-info col-sm-4">
                        <h5 class="card-text">Move to admin page</h5>
                    </a>
                    <a href="{% url 'logout' %}" class="col-sm-4 text-right">
                        <p class="text-danger card-link mb-0">
                            Log out
                        </p>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-10 mt-5 mx-auto flex-row">
            <h1 class="text-center text-uppercase font-weight-bold">avalable category</h1>
            <div class="row mb-3 mx-auto mt-4">
                {% for cate in object_list|dictsort:"name" %}
                    <div class="col-4">
                        <div class="card border-info mb-3">
                            <div class="card-body">
                                <h3 class="card-title text-info mb-0 text-center">
                                    {{ cate.name }}
                                </h3>
                            </div>
                        </div>
                    </div>   
                {% endfor %}
            </div>
        </div>
        <div class="col-10 mx-auto">
            <div class="col-4 ml-auto">
                <a href="{% url 'account:category' %}">
                    <div class="btn btn-success ml-auto">
                        <h4 class="text-light mb-0">ADD CATEGORY</h4>
                    </div>
                </a>
            </div>
        </div> 
    {% else %}
    <div class="col-6 mx-auto">
        <div class="card">
            <div class="card-header">
                <h5 class="card-text">
                    Hi {{ user.username }}
                </h5>
            </div>
            <div class="card-body">
                <h4 class="card-text text-center">
                    What do you want to do?
                </h4>
            </div>
            <div class="card-footer d-flex flex-row justify-content-between">
                <a href="{% url 'home' %}">
                    <p class="card-link text-muted mb-0">
                        Explore this site
                    </p>
                </a>
                <a href="{% url 'logout' %}">
                    <p class="text-danger card-link mb-0">
                        Log out
                    </p>
                </a>
            </div>
        </div>
    </div>
</div>
    {% endif %}
{% endblock %}