accounts/urls.py
from django.urls import path

from . import views

app_name='account'
urlpatterns = [
    path('signup/', views.Signup.as_view(), name='signup'),
    path('user/', views.UserView.as_view(), name='account'),
    path('category/', views.CategoryListView.as_view(), name='category')
]

intekimdb/urls.py
from django.urls import path

from . import views


app_name='intekimdb'
urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('actors/', views.ActorListView.as_view(), name='actor_list'),
    path('actors/create/', views.ActorCreate.as_view(), name='actor_create'),
    path('actors/<int:pk>/', views.ActorDetailView.as_view(), name='actor_detail'),
    path('actors/<int:pk>/update/', views.ActorUpdate.as_view(), name='actor_update'),
    path('actors/<int:pk>/delete/', views.ActorDelete.as_view(), name='actor_delete'),
    path('movies/', views.MovieListView.as_view(), name='movie_list'),
    path('movies/create/', views.MovieCreate.as_view(), name='movie_create'),
    path('movies/<int:pk>/', views.MovieDetailView.as_view(), name='movie_detail'),
    path('movies/<int:pk>/update/', views.MovieUpdate.as_view(), name='movie_update'),
    path('movies/<int:pk>/delete/', views.MovieDelete.as_view(), name='movie_delete'),
    path('awards/', views.AwardListView.as_view(), name='award_list'),
    path('awards/create/', views.AwardCreate.as_view(), name='award_create'),
    path('awards/<int:pk>/', views.AwardDetailView.as_view(), name='award_detail'),
    path('awards/<int:pk>/update/', views.AwardUpdate.as_view(), name='award_update'),
    path('awards/<int:pk>/delete/', views.AwardDelete.as_view(), name='award_delete'),
    path('comment/<int:pk>/<int:id>/delete/', views.CommentDelete.as_view(), name='comment_delete'),
    path('comment/<int:pk>/<int:id>/update/', views.CommentUpdate.as_view(), name='comment_update'),

]


test_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView, RedirectView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/accounts/login/')),
    path('home/', TemplateView.as_view(template_name='home.html'), name='home'),
    path('home/', include('intekimdb.urls'), name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

intekimdb/forms.py
from django import forms
from .models import Actor, Movie, Award, Comment, Category
from django.contrib.contenttypes.models import ContentType
from django.utils.timezone import now


class CategoryForm(forms.ModelForm):
    
    class Meta:
        model = Category
        fields = ('name',)


class ActorForm(forms.ModelForm):
    
    class Meta:
        model = Actor
        fields = ('firstname', 'lastname', 'birthday', 'sex', 'nationality', 'alive', 'portrait')
        widgets = {
            'birthday': forms.DateInput(format='%d/%m/%Y', attrs={'class': 'datepicker'}),
        }

class MovieForm(forms.ModelForm):

    class Meta:
        model = Movie
        fields = ('title', 'description', 'release_date', 'category', 'actors', 'logo')

        widgets = {
            'release_date': forms.DateInput(format='%d/%m/%Y', attrs={'class': 'datepicker'}),
        }


class AwardForm(forms.ModelForm):

    class Meta:
        model = Award
        fields = ('name', 'kind', 'movies', 'actors', 'date')

        widgets = {
            'date': forms.DateInput(format='%d/%m/%Y', attrs={
                'class': 'datepicker'
            })
        }

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('entry_comment', )
        readonly_fields=('user', 'release_date')
        widgets = {
            'entry_comment': forms.TextInput(),
        }

    def save(self, comment_object, comment_user):
        comment = Comment()
        comment.entry_comment = self.cleaned_data['entry_comment']
        object_model = ContentType.objects.get_for_model(comment_object)
        comment.content_type = object_model
        comment.object_id = comment_object.id
        comment.user = comment_user
        comment.save()

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        # deleted form label
        self.fields['entry_comment'].label = ""        


class CommentEditForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('entry_comment', )
        readonly_fields=('user', 'release_date')
        widgets = {
            'entry_comment': forms.TextInput(attrs={'class': 'form-input'}),
        }
    

intekimdb/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse
from django.views import View
from django.urls import reverse_lazy

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormMixin
from django.views.generic import TemplateView

from .models import Movie, Actor, Award, Comment
from .forms import ActorForm, MovieForm, CommentForm, CommentEditForm



# -----------Comment view---------------
class CommentDelete(DeleteView):
    '''
    Delete a comment
    '''
    model = Comment

    def get_success_url(self):
        if self.request.POST.get("movie_cmt"):
            return reverse_lazy('intekimdb:movie_detail', kwargs={'pk': self.kwargs.get('id')})
        elif self.request.POST.get("actor_cmt"):
            return reverse_lazy('intekimdb:actor_detail', kwargs={'pk': self.kwargs.get('id')})
        elif self.request.POST.get("award_cmt"):
            return reverse_lazy('intekimdb:award_detail', kwargs={'pk': self.kwargs.get('id')})


class CommentUpdate(UpdateView):
    '''
    View to update a specific comment
    '''
    model = Comment
    form_class = CommentEditForm

    def get_object(self, querys_set=None):
        return Comment.objects.get(id=self.kwargs['pk'])

    def get_success_url(self):
        if self.request.POST.get("movie_cmt"):
            return reverse_lazy('intekimdb:movie_detail', kwargs={'pk': self.kwargs.get('id')})
        elif self.request.POST.get("actor_cmt"):
            return reverse_lazy('intekimdb:actor_detail', kwargs={'pk': self.kwargs.get('id')})
        elif self.request.POST.get("award_cmt"):
            return reverse_lazy('intekimdb:award_detail', kwargs={'pk': self.kwargs.get('id')})
        



# -----------Actor view---------------
class ActorListView(ListView):
    '''
    View list of actors including: actor's name, birthday, gender, 
    nationality.
    '''
    model = Actor
    paginate_by = 100  # if pagination is desired

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class ActorDetailView(DetailView, FormMixin):
    '''
    View detail of an actor
    '''
    model = Actor
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = Actor.objects.get(pk=self.kwargs.get('pk')).comments.all()
        context['edit_comment_form'] = CommentEditForm
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        p_object = Actor.objects.get(pk=self.kwargs.get('pk'))
        
        if form.is_valid():
            form.save(p_object, request.user)
            return redirect(reverse_lazy('intekimdb:actor_detail', kwargs={'pk': p_object.pk}))


class ActorCreate(CreateView):
    '''
    View to create a new actor
    '''
    form_class = ActorForm
    success_url = reverse_lazy('intekimdb:actor_list')  
    template_name = 'intekimdb/actor_form.html'


class ActorUpdate(UpdateView):
    '''
    View to update a specific actor
    '''
    model = Actor
    fields = '__all__'
    template_name_suffix = '_update_form'


class ActorDelete(DeleteView):
    '''
    Detele an an actor
    '''
    model = Actor
    success_url = reverse_lazy('intekimdb:actor_list')


# ---------Movie views---------------------------------
class MovieListView(ListView):
    '''
    View list of movies
    '''
    model = Movie
    paginate_by = 100  # if pagination is desired

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class MovieDetailView(DetailView, FormMixin):
    '''
    View detail of a specific movie
    '''
    model = Movie
    form_class = CommentForm

    def get_success_url(self):
        return reverse_lazy('intekimdb:movie_detail', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        context = super(MovieDetailView, self).get_context_data(**kwargs)
        context['comments'] = Movie.objects.get(pk=self.kwargs.get('pk')).comments.all()
        context['edit_comment_form'] = CommentEditForm
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        p_object = Movie.objects.get(pk=self.kwargs.get('pk'))
        if form.is_valid():
            form.save(p_object, request.user)
            return redirect(reverse_lazy('intekimdb:movie_detail', kwargs={'pk': p_object.pk}))


class MovieCreate(CreateView):
    '''
    view create a movie
    '''
    form_class = MovieForm
    success_url = reverse_lazy('intekimdb:movie_list')
    template_name = 'intekimdb/movie_form.html'


class MovieUpdate(UpdateView):
    '''
    View to update a specific movie
    '''
    model = Movie
    fields = '__all__'
    template_name_suffix = '_update_form'


class MovieDelete(DeleteView):
    '''
    Delete a movie
    '''
    model = Movie
    success_url = reverse_lazy('intekimdb:movie_list')


# ---------------Award views---------------------------------
class AwardListView(ListView):
    '''
    View of all awards
    '''
    model = Award
    paginate_by = 100  # if pagination is desired

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class AwardDetailView(DetailView, FormMixin):
    '''
    View detail of a specidfic award
    '''
    model = Award
    form_class = CommentForm
    template_name = 'intekimdb/award_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = Award.objects.get(pk=self.kwargs.get('pk')).comments.all()
        context['edit_comment_form'] = CommentEditForm
        return context
    
    def post(self, request, *args, **kwargs):
        form = self.get_form()
        p_object = Award.objects.get(pk=self.kwargs.get('pk'))
        if form.is_valid():
            form.save(p_object, request.user)
            return redirect(reverse_lazy('intekimdb:award_detail', kwargs={'pk': p_object.pk}))


class AwardCreate(CreateView):
    '''
    View create a new award
    '''
    model = Award
    fields = '__all__'
    success_url = reverse_lazy('intekimdb:award_list')


class AwardUpdate(UpdateView):
    '''
    View update an awards
    '''
    model = Award
    fields = '__all__'
    template_name_suffix = '_update_form'


class AwardDelete(DeleteView):
    '''
    Delete an award
    '''
    model = Award
    success_url = reverse_lazy('intekimdb:award_list')


# ------------The home view---------------
class IndexView(TemplateView):
    template_name = 'home.html'


templates/intekimdb/actor_confirm_delete.html
{% extends "home.html" %}
{% load add_attr %}

{% block title %}Actors{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    <div class="card">
        <div class="card-body">
            <h3 class="card-text text-center mb-4">Are you sure you want to delete "{{ object }}"?</h3>
            <div class="d-flex justify-content-center">
                <input type="submit" value="CONFIRM" class="btn btn-danger mr-2">
                <a href="{% url 'intekimdb:actor_list' %}" class="ml-2">
                    <div class="btn btn-success">RETURN</div>
                </a>
            </div>
        </div>
    </div>
</form>
{% endblock %}   

templates/intekimdb/actor_detail.html
{% extends "home.html" %}
{% load add_attr %}

{% block title %}Actor{% endblock %}


{% block content %}

{% if object %}
<div class="col-10 mx-auto">
    <div class="card">
        <div class="row no-gutters">

            <div class="col-4">
                <img src="{{ actor.portrait.url }}"  class="card-img"> 
            </div>
            <div class="col-8">
                <div class="card-body">
                    <h2 class="card-head mb-3">{{ actor.firstname }} {{ actor.lastname }}</h2>
                    <p class="card-text">
                        <strong>Birthday:</strong> {{ actor.birthday.date }}
                    </p>
                    <p class="card-text">
                        <strong>Gender:</strong> {{ actor.sex }}
                    </p>
                    <p class="card-text">
                        <strong>Nationality:</strong> {{ actor.nationality }}
                    </p>
                    <p class="card-text">Movies: 
                        {% for i in actor.movie_set.all %}
                        <a href="{% url 'intekimdb:movie_detail' i.id %}">
                            {{ i.title }}
                        </a>,
                        {% endfor %}...
                    </p>
                    {% if actor.alive %}
                    <div class="bg-info col-4 ml-auto rounded">
                        <h5 class="text-right text-white">ALIVE</h5>
                    </div>
                    {% else %}
                    <div class="bg-dark col-4 ml-auto rounded">
                        <h5 class="text-right text-white">DEAD</h5>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="card-body ml-auto justify-content-end d-flex">
        <a href="{% url 'intekimdb:actor_update' actor.id %}" class="mr-2">
            <div class="btn btn-primary">
                <h6 class="mb-0">Edit actor </h6>
            </div>
        </a>
        <a href="{% url 'intekimdb:actor_delete' actor.id %}">
            <div class="btn btn-danger">
                <h6 class="mb-0">Delete actor </h6>
            </div>
        </a>
    </div>
</div>

<!-- comment part -->
<div class="col-8 mx-auto mt-4">
    <div class="card">
        <div class="card-body pb-0">
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_entry_comment" class="col-4 col-form-label">Comment:</label>
                    <div class="col-12">
                        {{ form.entry_comment|add_attr:"class:form-control" }}
                    </div>
                    <div class="row col-12 mt-3">
                        <input class="btn btn-primary col-3 ml-auto py-1 font-weight-bold" type="submit" value="Comment" style="font-size: 13px">
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- list of comments -->
    <div class="d-flex flex-column-reverse">
        {% for comment in actor.comments.all %}
        <div class="card mt-3">
            <div class="card-body">
                <blockquote class="blockquote mb-0" style="font-size: 17px">
                    {{comment}}         
                    <footer class="blockquote-footer">{{ comment.user }}</footer>
                </blockquote>
            </div>
            <footer class="card-footer py-0" style="font-size: 13px">
                <div class="col-12 d-flex justify-content-start"> 
                    <button type="button" class="btn btn-default mr-2 text-muted px-1" data-toggle="modal" data-target="#myModal{{comment.id}}" style="font-size: 14px">Edit</button>
                    <!-- Modal -->
                    <div class="modal fade" id="myModal{{comment.id}}" role="dialog">
                        <div class="modal-dialog">
                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>
                                <form method='POST' action="{% url 'intekimdb:comment_update' comment.id actor.id %}">{% csrf_token %}
                                    <div class="modal-body">
                                        <div class="form-group row">
                                            <label for="id_edit_comment_form" class="col-form-label col-sm-3">Edit comment: </label>
                                            <div class="col-sm-8">
                                                {{ edit_comment_form.entry_comment|add_attr:"class:form-control " }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default mr-auto" data-dismiss="modal">Close</button>
                                        <input type="submit" class="btn btn-danger" value="Commit"  name="actor_cmt">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <button type="button" class="btn btn-default text-danger" data-toggle="modal" data-target="#myModal1{{comment.id}}" style="font-size: 14px">Delete</button>
                    <!-- Modal -->
                    <div class="modal fade" id="myModal1{{comment.id}}" role="dialog">
                        <div class="modal-dialog">
                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal"><strong>&times;</strong></button>
                                </div>
                                <form method='POST' action="{% url 'intekimdb:comment_delete' comment.id actor.id %}" >{% csrf_token %}
                                    <div class="modal-body">
                                        <h2 class="text-center">Are you sure?</h2>
                                        
                                    </div>
                                    <div class="modal-footer d-flex justify-content-around">
                                        <input type="submit" class="btn btn-danger py-1 col-3" value="Yes" name="actor_cmt">
                                        <button type="button" class="btn btn-info py-1 col-3" data-dismiss="modal">No</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <p class="text-muted mb-0 ml-auto align-self-center">
                        {{ comment.release_date }}
                    </p>
                </div>
            </footer>
        </div>
        {%endfor%}
    </div>
</div>
{% endif %}
{% endblock %}   


templates/intekimdb/actor_form.html
{% extends "home.html" %}
{% load add_attr %}

{% block title %}Actor{% endblock %}



{% block content %}
  <div class="card border-0 bg-light">
    <div class="card-body">
      <h2 class="text-center mb-4">Add new Actor</h2>
      <form method="post" enctype="multipart/form-data">{% csrf_token %}
        <div class="form-group row">
          <label for="id_firstname" class="col-sm-2 col-form-label">
            Actor firstname
          </label>
          <div class="col-sm-10">
            {{ form.firstname|add_attr:"class:form-control" }}
          </div>
          {{ form.firstname.errors }}
        </div>
        <div class="form-group row">
          <label for="lastname" class="col-sm-2 col-form-label">
            Actor lastname
          </label>
          <div class="col-sm-10">
            {{ form.lastname|add_attr:"class:form-control" }}
          </div>
          {{ form.lastname.errors }}
        </div>
        <div class="form-group row">
          <label for="id_logo" class="col-sm-2 col-form-label">
            Portrait
          </label>
          <div class="col-sm-10">
            {{ form.portrait|add_attr:"class:form-control" }}
          </div>
          {{ form.portrait.errors }}
        </div>
        <div class="form-group row">
          <label for="id_title" class="col-sm-2 col-form-label">
            Birthday
          </label>
          <div class="col-sm-5">
            {{ form.birthday|add_attr:"class:form-control input-date" }}
          </div>
          {{ form.brithday.errors }}
        </div>
        <div class="from-group row">
          <label for="id_sex" class="col-sm-2 col-form-label">Gender</label>
          <div class="col-sm-5">
            {{ form.sex|add_attr:"class:form-control" }}
          </div>
        </div>
        <div class="form-group row">
          <label for="id_nationality" class="col-sm-2 col-form-label">Nationality</label>
          <div class="col-sm-5">
            {{ form.nationality|add_attr:"class:form-control"}}
          </div>
          {{ form.nationality.errors}}
        </div>
        <div class="form-group row">
          <label for="{{ form.alive.id }}" class="col-sm-2 col-form-label">Alive</label>
          <div class="col-sm-5 form-check align-content-center">
            {{ form.alive|add_attr:"class: form-check-input ml-2" }}
          </div>
        </div>
        
        <div class="row">
          <button class="mt-5 btn btn-primary mx-auto col-sm-6">
            <h4 class="mb-0 mx-auto">SAVE</h4>
          </button>
        </div>
        <div class="col-10">
          {{ form.errors.as_text }}
        </div>
      </form>
    </div>
  </div>
{% endblock %}     

{% block head %}
  <script>
    $( function() {
      $( "#id_birthday" ).datepicker({
        changeMonth: true,
        changeYear: true,
        yearRange: "1800:2020",
        format: "dd/MM/yyyy"
      });
    } );
  </script>
{% endblock %}

templates/intekimdb/comment_update_form.html
{% extends "home.html" %}
{% load add_attr %}

{% block title %}Movie{% endblock %}

{% block head %}
{% endblock %}  

{% block content %}
<form method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="OK">
</form>
{% endblock %}    

templates/intekimdb/movie_detail.html
{% extends "home.html" %}
{% load add_attr %}

{% block title %}Movie{% endblock %}

{% block content %}
{% if object %}
<div class="col-8 mx-auto">
    <div class="card">
        <img src="{{movie.logo.url}}"  class="card-img-top"> 
        <div class="card-body">
            <h2 class="card-head">{{ movie.title }}</h2>
            <p class="card-text text-muted" style="font-size: 15px"><strong>Release date:</strong> {{ movie.release_date.date }}</p>
            <p class="card-text">{{ movie.description }}</p>
            <p class="card-text"><strong>Actors: </strong>
                {% for actor in movie.actors.all %}
                <a href="{% url 'intekimdb:actor_detail' actor.id %}">
                    {{ actor.firstname }} {{ actor.lastname }}
                </a>,
                {% endfor %}...
            </p>
            <p class="card-text text-muted" style="font-size: 15px">
                {% for i in movie.category.all %}
                    #{{ i.name }} 
                {% endfor %}
            </p>
        </div>
    </div>
    <div class="mt-3 d-flex justify-content-end ">
        <a href="{% url 'intekimdb:movie_update' movie.id %}" class="mr-2">
            <div class="btn btn-primary">
                <h6 class="mb-0">Edit movie </h6>
            </div>
        </a>
        <a href="{% url 'intekimdb:movie_delete' movie.id %}">
            <div class="btn btn-danger">
                <h6 class="mb-0">Delete movie </h6>
            </div>
        </a>
    </div>
</div>

<!-- comment part -->
<div class="col-8 mx-auto mt-4">
    <div class="card">
        <div class="card-body pb-0">
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_entry_comment" class="col-4 col-form-label">Comment:</label>
                    <div class="col-12">
                        {{ form.entry_comment|add_attr:"class:form-control" }}
                    </div>
                    <div class="row col-12 mt-3">
                        <input class="btn btn-primary col-3 ml-auto py-1 font-weight-bold" type="submit" value="Comment" style="font-size: 13px">
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- list of comments -->
    <div class="d-flex flex-column-reverse">
        {% for comment in movie.comments.all %}
        <div class="card mt-3">
            <div class="card-body">
                <blockquote class="blockquote mb-0" style="font-size: 17px">
                    {{comment}}         
                    <footer class="blockquote-footer">{{ comment.user }}</footer>
                </blockquote>
            </div>
            <footer class="card-footer py-0" style="font-size: 13px">
                <div class="col-12 d-flex justify-content-start"> 
                    <button type="button" class="btn btn-default mr-2 text-muted px-1" data-toggle="modal" data-target="#myModal{{comment.id}}" style="font-size: 14px">Edit</button>
                    <!-- Modal -->
                    <div class="modal fade" id="myModal{{comment.id}}" role="dialog">
                        <div class="modal-dialog">
                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>
                                <form method='POST' action="{% url 'intekimdb:comment_update' comment.id movie.id %}">{% csrf_token %}
                                    <div class="modal-body">
                                        <div class="form-group row">
                                            <label for="id_edit_comment_form" class="col-form-label col-sm-3">Edit comment: </label>
                                            <div class="col-sm-8">
                                                {{ edit_comment_form.entry_comment|add_attr:"class:form-control " }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default mr-auto" data-dismiss="modal">Close</button>
                                        <input type="submit" class="btn btn-danger" value="Commit"  name="movie_cmt">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <button type="button" class="btn btn-default text-danger" data-toggle="modal" data-target="#myModal1{{comment.id}}" style="font-size: 14px">Delete</button>
                    <!-- Modal -->
                    <div class="modal fade" id="myModal1{{comment.id}}" role="dialog">
                        <div class="modal-dialog">
                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal"><strong>&times;</strong></button>
                                </div>
                                <form method='POST' action="{% url 'intekimdb:comment_delete' comment.id movie.id %}" >{% csrf_token %}
                                    <div class="modal-body">
                                        <h2 class="text-center">Are you sure?</h2>
                                        
                                    </div>
                                    <div class="modal-footer d-flex justify-content-around">
                                        <input type="submit" class="btn btn-danger py-1 col-3" value="Yes" name="movie_cmt">
                                        <button type="button" class="btn btn-info py-1 col-3" data-dismiss="modal">No</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <p class="text-muted mb-0 ml-auto align-self-center">
                        {{ comment.release_date }}
                    </p>
                </div>
            </footer>
        </div>
        {%endfor%}
    </div>
</div>
{% endif %}
{% endblock %}   

templates/intekimdb/movie_list.html
{% extends "home.html" %}
{% load add_attr %}


{% block title %}Movies{% endblock %}

{% block content %}
<div class="col-12 mx-auto">
    <div class="row justify-content-center mb-5">
        <h1 class="font-weight-bold text-uppercase">Movies</h1>
    </div>
    <div class="card-deck">
        {% for movie in object_list %}
        <div class="col-4">
            <div class="card mb-3">
                <img src="{{ movie.logo.url }}" alt="movie_logo" class="card-img-top img-ava">
                <div class="card-body">
                    <h3 class="card-title">{{ movie.title }}</h3>
                    <p class="card-text text-muted" style="font-size: 14px"><strong>Release date:</strong> {{ movie.release_date.date }}</p>
                    <p class="card-text text-muted" style="font-size: 15px">
                        {% for cate in movie.category.all %}
                        #{{ cate }} 
                        {% endfor %}
                    </p>
                </div>
                <a href="{% url 'intekimdb:movie_detail' movie.id %}" class="card-link card-footer">
                    <p class="mb-0">>> Read more</p>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="row mt-5">
        <div class="col-3 ml-auto">
            <a href="{% url 'intekimdb:movie_create' %}">
                <div class="btn btn-success">
                    <h3 class="text-light mb-0">ADD MOVIE</h3>
                </div>
            </a>
        </div>
    </div>
</div>
{% endblock %}   



